title: Ricette AI
description: Ricette generate con AI e pubblicate via Jekyll
lang: it

theme: minima
baseurl: "/jekyll-recipe-ai"
url: "https://antonio-backend-projects.github.io/jekyll-recipe-ai"

future: false

paginate: 20  # Numero di post per pagina
paginate_path: "/page:num"  # URL delle pagine successive


plugins:
  - jekyll-paginate
